# Generated by Django 3.0.8 on 2020-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0003_remove_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
