# Generated by Django 3.0.8 on 2020-08-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0004_artist_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
