# Generated by Django 3.0.8 on 2020-08-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0005_auto_20200831_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artists',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
    ]
